\c testdb;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA design_test TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA design_test GRANT SELECT, INSERT, UPDATE, DEFAULT ON TABLES TO app_user;